/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ErrorBoundaryH5: typeof import('./../../../../packages/h5/components/src/ErrorBoundaryH5/index.vue')['default']
    FilterDrawer: typeof import('./../../../../packages/h5/components/src/FilterDrawer/index.vue')['default']
    NavBar: typeof import('./../../../../packages/h5/components/src/NavBar/index.vue')['default']
    PageContainer: typeof import('./../../../../packages/h5/components/src/PageContainer/index.vue')['default']
    ProList: typeof import('./../../../../packages/h5/components/src/ProList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeArea: typeof import('./../../../../packages/h5/components/src/SafeArea/index.vue')['default']
    SkeletonH5: typeof import('./../../../../packages/h5/components/src/SkeletonH5/index.vue')['default']
    SvgIconH5: typeof import('./../../../../packages/h5/components/src/SvgIconH5/index.vue')['default']
    TabBarLayout: typeof import('./../../../../packages/h5/components/src/TabBarLayout/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
